void test_subBytes();
void test_shiftRows();
void test_keyExpanssion();
void test_mixed_column();
void test_inv_mixed_column();
void test_encrypt_128();
void test_encrypt_192();
void test_encrypt_256();
void test_encrypt_CBC_128();
void test_encrypt_CBC_192();
void test_encrypt_CBC_256();
void tests_file_encrypt_128();
void tests_file_encrypt_192();
void tests_file_encrypt_256();
char* encryption_key(int sizekey);